# Generated by Django 3.2.4 on 2021-07-09 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keiba_forecasts', '0006_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Post',
        ),
    ]
